;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Rooms",DevComment="Gameplay tags used for the room generation")
+GameplayTagList=(Tag="Rooms.Challenge",DevComment="A challenge room is a large room that will take some time and skill to get through.")
+GameplayTagList=(Tag="Rooms.EntityAllowed",DevComment="Can entites spawn in that room?")
+GameplayTagList=(Tag="Rooms.HidingSpot",DevComment="Room containing an hiding spot.")
+GameplayTagList=(Tag="Rooms.Puzzle",DevComment="A puzzle room is a timed room in which players will have to think to get through")
+GameplayTagList=(Tag="Rooms.Saferoom",DevComment="Saferooms are rooms between floors or important parts. Players cannot be killed in that room (unless told otherwise).")
+GameplayTagList=(Tag="Rooms.Teleporter",DevComment="A set of teleporter rooms that will spawn if the generation cannot find a place to spawn without colliding with other rooms.")
+GameplayTagList=(Tag="Rooms.Tunnel",DevComment="Is the current room a tunnel?")
+GameplayTagList=(Tag="Rooms.Tunnel.End",DevComment="Rooms that can end the tunnel section.")
+GameplayTagList=(Tag="Rooms.Tunnel.Normal",DevComment="A normal tunnel. Can be placed between Start and End Tunnels.")
+GameplayTagList=(Tag="Rooms.Tunnel.Start",DevComment="Rooms that will start a Tunnel section.")
+GameplayTagList=(Tag="Rooms.Tutorial",DevComment="All rooms compatible with the tutorial floor.")
+GameplayTagList=(Tag="Rooms.Water",DevComment="Is the room submerged?")

